name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ libgtest-dev build-essential
        cd /usr/src/googletest
        sudo cmake .
        sudo make
        sudo cp lib/*.a /usr/lib

    - name: Build and Test
      run: |
        mkdir build && cd build
        cmake ..
        make
        ctest --output-on-failure
        
    - name: Check Coverage
      run: |
        cd build
        ./banking_tests
        gcovr -r .. --branches --print-summary
        gcovr -r .. --html-details coverage.html
